name: Update BookSource

on:
  workflow_dispatch:
  push:
    paths:
      - '.history/**'

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Run Script
        run: python3 ./.github/scripts/src_sort.py

      - name: Push
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Robot"
          git add .
          git commit -m "update" -a
          git push origin master
